language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.6

# Deploy executables to Github release tags
deploy:
  provider: releases
  api_key:
    secure: b64ne3ch0Yc5wCkyJxyJ/T2vsdy4ksFIqcM7fCTe/+en8pwpPk9NL+ywHO61SgAwW1xwyswt/rvdJQz01ZuaaFHqljg1UM/zEWIggKDqVp2EZ6OCztg8qhqth+cRkIzmIdwiSEOX1f+Ju+CrdYfWnReHESZsUgLHXte2tejWHZwcbxoPXiE1pKXzEz0GmR81k+0SD+zZA9iVcG/J0pFLmJYgiiL9AzTzHtp5EeMCR+aI193yflUE3jhVoyFsZLSLtJX57CpcSF2ydX/NlDnbnjRz2ok2TVmXWJnj97TRBqh876qi1TsZzOOwmsAU/pkUwUkjCMJVHZG4i4n3q9sOnSf6TZxwGfrIoKflhODhFgXJOkOMIAJdPYB0Uw9CMekRthZMuYzB7874nwBqjqe9N15KzizW2bLniAtq7dd7TVOoUHBKO4G/GSu3oMxl/uuaHzJ1z+G7k+2/IS3PRgISKxce1rVRVoAF/xq9vozbvZhKnrBVAu9FofLiebhPxRgsJZZQdRPtXvd7ad8PnxjAFO1p53wbt3srviK4ruLBeRAVXSgL1760xlu1501UhJKO9z2MHY2xb+MvZ4Iy94eSrrSGSrbbK3OpNlWnkfcbmRp1MIhtoyGnotLr251AwyXKo/o+80xjoAGsZ8ZYbhpAj7fzb1jwxuHMma96wv67dqo=
  file: "awsu-$(uname -s)-$(uname -m)"
  skip_cleanup: true
  on:
    tags: true

# Code coverage for master branch using https://codecov.io/github/meltwater/awsu
after_success:
  - if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then bash <(curl -s https://codecov.io/bash); fi
