language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.6

# Deploy executables to Github release tags
deploy:
  provider: releases
  api_key:
    secure: bqWkf0nLwzvxzcuotWrWPZXcXdR5PXYK+fk4wFSCMlBpkl2Gpb1OtoP0kCuKnF/W5a5D1c2kAV9czPeBUx8T/y0PcAlTl76QkOp/l2QMYky6mHyFG8GxV529aakxZFc6yBinO2jHmTYJB4CuixV8yyjjC1OfuMaAfXCHQhIxbR7lRmGyKdQM9oFs8mIg5wgGCW2d6X261d+PTe6WDNjh0wW19RyXaRY6HPd/cg0TNhebfGIJOW5bsX4dOafTs0t/laX0A4K8jdQHB+WZTM++KJcEhpHir35IEt8LB2Ifj7wI6P+HpAT9a8ooiSdEv8D6awRnfifPZLj1HTx0GoB1b+GM4Ejni+XkIqVW1kW+kz8veZ1Fi9vP6ljzzoL8kOeV4UdVs/n/GGO/v3p+lISlRFaXvtxrDvhmNuZfe/izq152Cn4jBMhOi1oEVYUALlwaq5gd8Aqv8WG8CEzUHMCJYnyhSzHgkn54nxwxqLifvG2gJ1ZW6as3EA2/eyqBqi/aoQ3Kf8lUS5b/ev9Cg8FX31QxhmDPx2ZA6zX+rRKz3nJ92bOHwrzi50i797B0vfr7o+JFVNuDMiIKDBpHp1xcC1YzRwgGBI+l8qSdFEeMHfvzfP68r8Bg8OrMGrzca49cxqt5SwwcYkN6AlvYcflRMDyy++QunpkOLmQfwnEc53U=
  file: "awsu-$(uname -s)-$(uname -m)"
  skip_cleanup: true
  on:
    tags: true

# Code coverage for master branch using https://codecov.io/github/meltwater/awsu
after_success:
  - if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then bash <(curl -s https://codecov.io/bash); fi
